# -*- coding: utf-8 -*-
"""filter_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jUOOOK0XLX7Mpmia1IR8hvdDNuTjCXi
"""

import pandas as pd


baza = {
    "FISH": [
        "Aliyev Vali", "Zumratova Qimmat", "Diyorov Bekzod", "Shahramov Rustam",
        "Malikova Nilufar", "Maksudova Gulbahor", "Bunyodov Ravshan", "Nodirova Shirin",
        "Otabekov Bunyod", "Diyorova Malika"
    ],
    "Yoshi": [25, 34, 19, 40, 27, 36, 22, 29, 18, 45],
    "Jinsi": ["Erkak", "Ayol", "Erkak", "Erkak", "Ayol", "Ayol", "Erkak", "Ayol", "Erkak", "Ayol"],
    "Ta'lim maskani": ['1-maktab', '2-maktab', '1-maktab', '2-maktab', '1-maktab', '2-maktab', '1-maktab', '2-maktab', '1-maktab', '2-maktab'],
    "Manzili": ['Farg\'ona shahar', 'Mafg\'ilon shahar', 'Farg\'ona shahar', 'Mafg\'ilon shahar', 'Farg\'ona shahar', 'Mafg\'ilon shahar', 'Farg\'ona shahar', 'Mafg\'ilon shahar', 'Farg\'ona shahar', 'Mafg\'ilon shahar']
}


db = pd.DataFrame(baza)


print(db)



filter = db[(db['Yoshi'] < 25) & (db['Jinsi'] == "Erkak")]
print(filter)

youngest = db[db['Yoshi'] == db['Yoshi'].min()]
oldest = db[db['Yoshi'] == db['Yoshi'].max()]

print("Eng yosh inson:")
print(youngest)

print("Eng yoshi ulug' inson")
print(oldest)



fargona_erkaklar = db[(db["Jinsi"] == "Erkak") & (db["Manzili"] == "Toshkent shahar")]

print(fargona_erkaklar)